name: Build
on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup override set stable
          rustup update stable
          rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt --check --all

      - name: Run clippy
        run: cargo clippy -- -Dwarnings

      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build
